version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 24
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - if [[ $CODEBUILD_BUILD_SUCCEEDING == 0 ]]; then exit 1; fi
      - echo Build completed
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: out
